# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def ordenar_lista(numeros: list[int]):
  numeros_ordenados = sorted(numeros)
  return numeros_ordenados

  lista = [42, 12, 9, 73, 51, 22]
  resultado = ordenar_lista(lista)
  print(resultado)