# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

def exportar_csv(pessoas: list, nome_arquivo: str):
  df = pd.DataFrame(pessoas)
  df.to_csv(nome_arquivo, index=False)
  print(f"Arquivo '{nome_arquivo}' exportado com sucesso!")

  def criar_pessoa(nome: str, idade: int, id: int):
    pessoa = {
        "id" : id,
        "nome" : nome,
        "idade" :idade
    }
    return pessoa
  def adicionar_gostos(pessoas: list, gostos: list):
    mapa_gostos = {g["id"]: g["gostos"] for g in gostos}

    resultado = []
    for pessoa in pessoas[:5]:
      nova_pessoa = pessoa.copy()
      nova_pessoa["gostos"] = mapa_gostos.get(pessoa["id"], [])

      resultado.append(nova_pessoa)

    return resultado
    pessoas = [
        criar_pessoa("Marcos", 28, 1),
        criar_pessoa("Ana", 24, 2),
        criar_pessoa("Carlos", 30, 3),
        criar_pessoa("Julia", 22, 4),
        criar_pessoa("Pedro", 27, 5),
        criar_pessoa("Laura", 26, 6)
    ]
    gostos = [
        {"id": 1, "gostos": ["Música", "Futebol"]},
        {"id": 2, "gostos": ["Leitura", "Cinema"]},
        {"id": 3, "gostos": ["Viagem"]},
        {"id": 4, "gostos": ["Dança", "Esportes"]},
        {"id": 5, "gostos": ["Tecnologia", "Culinária"]},
        {"id": 6, "gostos": ["Moda"]}
    ]
    resultado = adicionar_gostos(pessoas, gostos)
    exportar_csv(resultado, "pessoas.csv")