# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def criar_pessoa(nome: str, idade: int, id: int):
    pessoa = {
        "id" : id,
        "nome" : nome,
        "idade" :idade
    }
    p1 = criar_pessoa("Marcos", 28, 1)
    p2 = criar_pessoa("Ana", 24, 2)
    p3 = criar_pessoa("Carlos", 30, 3)
    print(p1)
    print(p2)
    print(p3)